# Skellett the addon with the beast name!
# By the one and only LimeGlass

version: "@version@"

# The syntax debug will change the colour of the found syntax option. That way it's easier to tell if that syntax was registered out of all the debug messages.
syntaxDebug: "Sound"
debug: false

# Checks for the latest Skellett version from Spigot.
VersionChecker: true

# Save input so you can get the last known client border data of a player in an expression.
ClientWorldBordersSave: true
# This makes the client border syntax modify the border of the world a player is in and not make them client side.
NormalBorders: false

# Broadcast all the syntax that didn't register to the console.
NotRegisteredSyntax: false

# Disables the warning message saying a syntax can't be registered due to current spigot version.
DisableCompatableWarning: false

# Disables the message saying the total number of syntax registered and the final registered message.
DisableRegisteredInfo: false

# In the center message effect. This changes the length of the centered character.
CenterMessageSize: 62

# Enables 1.8 pvp combat speeds if you run a 1.11 server with protocolsupport.
Enable1_8pvp: false

PluginHooks:
    LibsDisguises: false
    # If you use Citizens https://www.spigotmc.org/resources/citizens.13811/
    Npc: false
    # If you use Holograms https://www.spigotmc.org/resources/holograms.4924/
    Holograms: false
    # If you use CorpseReborn https://www.spigotmc.org/resources/corpsereborn.29875/
    CorpseReborn: false
 
    # If you use PlayerPoints https://dev.bukkit.org/projects/playerpoints
    PlayerPoints: false
